version: "3"
services:
  server:
    image: node:12-alpine
    working_dir: /server
    volumes:
      - ./server:/server:cached
    command: npm run dev
    environment:
      NODE_ENV: development
      PORT: 9090
      MONGO_URI: 'mongodb://mongo:27017/thingy'
    ports:
      - 9090:9090
    expose:
      - 9090

  client:
    image: node:12-alpine
    working_dir: /client
    volumes:
      - ./client:/client:cached
    command: npm start
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    expose:
      - 3000

  mongo:
    image: mvertes/alpine-mongo
    working_dir: /db
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017
